#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanHoa.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ShopBanHoa")]
	public partial class DB_ShopBanHoaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBinhLuan(BinhLuan instance);
    partial void UpdateBinhLuan(BinhLuan instance);
    partial void DeleteBinhLuan(BinhLuan instance);
    partial void InsertHoa(Hoa instance);
    partial void UpdateHoa(Hoa instance);
    partial void DeleteHoa(Hoa instance);
    partial void InsertChiTietDonDatHang(ChiTietDonDatHang instance);
    partial void UpdateChiTietDonDatHang(ChiTietDonDatHang instance);
    partial void DeleteChiTietDonDatHang(ChiTietDonDatHang instance);
    partial void InsertDangKy(DangKy instance);
    partial void UpdateDangKy(DangKy instance);
    partial void DeleteDangKy(DangKy instance);
    partial void InsertDoanhThu(DoanhThu instance);
    partial void UpdateDoanhThu(DoanhThu instance);
    partial void DeleteDoanhThu(DoanhThu instance);
    partial void InsertDonDatHang(DonDatHang instance);
    partial void UpdateDonDatHang(DonDatHang instance);
    partial void DeleteDonDatHang(DonDatHang instance);
    partial void InsertGioHang(GioHang instance);
    partial void UpdateGioHang(GioHang instance);
    partial void DeleteGioHang(GioHang instance);
    #endregion
		
		public DB_ShopBanHoaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ShopBanHoaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_ShopBanHoaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_ShopBanHoaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_ShopBanHoaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_ShopBanHoaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BinhLuan> BinhLuans
		{
			get
			{
				return this.GetTable<BinhLuan>();
			}
		}
		
		public System.Data.Linq.Table<Hoa> Hoas
		{
			get
			{
				return this.GetTable<Hoa>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietDonDatHang> ChiTietDonDatHangs
		{
			get
			{
				return this.GetTable<ChiTietDonDatHang>();
			}
		}
		
		public System.Data.Linq.Table<DangKy> DangKies
		{
			get
			{
				return this.GetTable<DangKy>();
			}
		}
		
		public System.Data.Linq.Table<DoanhThu> DoanhThus
		{
			get
			{
				return this.GetTable<DoanhThu>();
			}
		}
		
		public System.Data.Linq.Table<DonDatHang> DonDatHangs
		{
			get
			{
				return this.GetTable<DonDatHang>();
			}
		}
		
		public System.Data.Linq.Table<GioHang> GioHangs
		{
			get
			{
				return this.GetTable<GioHang>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BinhLuan")]
	public partial class BinhLuan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBinhLuan;
		
		private System.Nullable<int> _MaHoa;
		
		private System.Nullable<int> _MaKhachHang;
		
		private System.Nullable<int> _DiemDanhGia;
		
		private string _NoiDungBinhLuan;
		
		private System.Nullable<System.DateTime> _ThoiGianBinhLuan;
		
		private EntityRef<Hoa> _Hoa;
		
		private EntityRef<DangKy> _DangKy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBinhLuanChanging(int value);
    partial void OnMaBinhLuanChanged();
    partial void OnMaHoaChanging(System.Nullable<int> value);
    partial void OnMaHoaChanged();
    partial void OnMaKhachHangChanging(System.Nullable<int> value);
    partial void OnMaKhachHangChanged();
    partial void OnDiemDanhGiaChanging(System.Nullable<int> value);
    partial void OnDiemDanhGiaChanged();
    partial void OnNoiDungBinhLuanChanging(string value);
    partial void OnNoiDungBinhLuanChanged();
    partial void OnThoiGianBinhLuanChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianBinhLuanChanged();
    #endregion
		
		public BinhLuan()
		{
			this._Hoa = default(EntityRef<Hoa>);
			this._DangKy = default(EntityRef<DangKy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBinhLuan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaBinhLuan
		{
			get
			{
				return this._MaBinhLuan;
			}
			set
			{
				if ((this._MaBinhLuan != value))
				{
					this.OnMaBinhLuanChanging(value);
					this.SendPropertyChanging();
					this._MaBinhLuan = value;
					this.SendPropertyChanged("MaBinhLuan");
					this.OnMaBinhLuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoa", DbType="Int")]
		public System.Nullable<int> MaHoa
		{
			get
			{
				return this._MaHoa;
			}
			set
			{
				if ((this._MaHoa != value))
				{
					if (this._Hoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHoaChanging(value);
					this.SendPropertyChanging();
					this._MaHoa = value;
					this.SendPropertyChanged("MaHoa");
					this.OnMaHoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Int")]
		public System.Nullable<int> MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._DangKy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemDanhGia", DbType="Int")]
		public System.Nullable<int> DiemDanhGia
		{
			get
			{
				return this._DiemDanhGia;
			}
			set
			{
				if ((this._DiemDanhGia != value))
				{
					this.OnDiemDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._DiemDanhGia = value;
					this.SendPropertyChanged("DiemDanhGia");
					this.OnDiemDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungBinhLuan", DbType="NVarChar(MAX)")]
		public string NoiDungBinhLuan
		{
			get
			{
				return this._NoiDungBinhLuan;
			}
			set
			{
				if ((this._NoiDungBinhLuan != value))
				{
					this.OnNoiDungBinhLuanChanging(value);
					this.SendPropertyChanging();
					this._NoiDungBinhLuan = value;
					this.SendPropertyChanged("NoiDungBinhLuan");
					this.OnNoiDungBinhLuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBinhLuan", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianBinhLuan
		{
			get
			{
				return this._ThoiGianBinhLuan;
			}
			set
			{
				if ((this._ThoiGianBinhLuan != value))
				{
					this.OnThoiGianBinhLuanChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBinhLuan = value;
					this.SendPropertyChanged("ThoiGianBinhLuan");
					this.OnThoiGianBinhLuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hoa_BinhLuan", Storage="_Hoa", ThisKey="MaHoa", OtherKey="MaHoa", IsForeignKey=true)]
		public Hoa Hoa
		{
			get
			{
				return this._Hoa.Entity;
			}
			set
			{
				Hoa previousValue = this._Hoa.Entity;
				if (((previousValue != value) 
							|| (this._Hoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Hoa.Entity = null;
						previousValue.BinhLuans.Remove(this);
					}
					this._Hoa.Entity = value;
					if ((value != null))
					{
						value.BinhLuans.Add(this);
						this._MaHoa = value.MaHoa;
					}
					else
					{
						this._MaHoa = default(Nullable<int>);
					}
					this.SendPropertyChanged("Hoa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DangKy_BinhLuan", Storage="_DangKy", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public DangKy DangKy
		{
			get
			{
				return this._DangKy.Entity;
			}
			set
			{
				DangKy previousValue = this._DangKy.Entity;
				if (((previousValue != value) 
							|| (this._DangKy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DangKy.Entity = null;
						previousValue.BinhLuans.Remove(this);
					}
					this._DangKy.Entity = value;
					if ((value != null))
					{
						value.BinhLuans.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(Nullable<int>);
					}
					this.SendPropertyChanged("DangKy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hoa")]
	public partial class Hoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHoa;
		
		private string _TenHoa;
		
		private string _MoTaHoa;
		
		private int _GiaBan;
		
		private int _SoLuongTonKho;
		
		private string _LoaiHoa;
		
		private string _MauHoa;
		
		private string _KichThuoc;
		
		private System.Nullable<int> _KhuyenMai;
		
		private string _AnhHoa;
		
		private EntitySet<BinhLuan> _BinhLuans;
		
		private EntitySet<ChiTietDonDatHang> _ChiTietDonDatHangs;
		
		private EntitySet<GioHang> _GioHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaChanging(int value);
    partial void OnMaHoaChanged();
    partial void OnTenHoaChanging(string value);
    partial void OnTenHoaChanged();
    partial void OnMoTaHoaChanging(string value);
    partial void OnMoTaHoaChanged();
    partial void OnGiaBanChanging(int value);
    partial void OnGiaBanChanged();
    partial void OnSoLuongTonKhoChanging(int value);
    partial void OnSoLuongTonKhoChanged();
    partial void OnLoaiHoaChanging(string value);
    partial void OnLoaiHoaChanged();
    partial void OnMauHoaChanging(string value);
    partial void OnMauHoaChanged();
    partial void OnKichThuocChanging(string value);
    partial void OnKichThuocChanged();
    partial void OnKhuyenMaiChanging(System.Nullable<int> value);
    partial void OnKhuyenMaiChanged();
    partial void OnAnhHoaChanging(string value);
    partial void OnAnhHoaChanged();
    #endregion
		
		public Hoa()
		{
			this._BinhLuans = new EntitySet<BinhLuan>(new Action<BinhLuan>(this.attach_BinhLuans), new Action<BinhLuan>(this.detach_BinhLuans));
			this._ChiTietDonDatHangs = new EntitySet<ChiTietDonDatHang>(new Action<ChiTietDonDatHang>(this.attach_ChiTietDonDatHangs), new Action<ChiTietDonDatHang>(this.detach_ChiTietDonDatHangs));
			this._GioHangs = new EntitySet<GioHang>(new Action<GioHang>(this.attach_GioHangs), new Action<GioHang>(this.detach_GioHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHoa
		{
			get
			{
				return this._MaHoa;
			}
			set
			{
				if ((this._MaHoa != value))
				{
					this.OnMaHoaChanging(value);
					this.SendPropertyChanging();
					this._MaHoa = value;
					this.SendPropertyChanged("MaHoa");
					this.OnMaHoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHoa", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TenHoa
		{
			get
			{
				return this._TenHoa;
			}
			set
			{
				if ((this._TenHoa != value))
				{
					this.OnTenHoaChanging(value);
					this.SendPropertyChanging();
					this._TenHoa = value;
					this.SendPropertyChanged("TenHoa");
					this.OnTenHoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTaHoa", DbType="NVarChar(MAX)")]
		public string MoTaHoa
		{
			get
			{
				return this._MoTaHoa;
			}
			set
			{
				if ((this._MoTaHoa != value))
				{
					this.OnMoTaHoaChanging(value);
					this.SendPropertyChanging();
					this._MoTaHoa = value;
					this.SendPropertyChanged("MoTaHoa");
					this.OnMoTaHoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBan", DbType="Int NOT NULL")]
		public int GiaBan
		{
			get
			{
				return this._GiaBan;
			}
			set
			{
				if ((this._GiaBan != value))
				{
					this.OnGiaBanChanging(value);
					this.SendPropertyChanging();
					this._GiaBan = value;
					this.SendPropertyChanged("GiaBan");
					this.OnGiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongTonKho", DbType="Int NOT NULL")]
		public int SoLuongTonKho
		{
			get
			{
				return this._SoLuongTonKho;
			}
			set
			{
				if ((this._SoLuongTonKho != value))
				{
					this.OnSoLuongTonKhoChanging(value);
					this.SendPropertyChanging();
					this._SoLuongTonKho = value;
					this.SendPropertyChanged("SoLuongTonKho");
					this.OnSoLuongTonKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHoa", DbType="NVarChar(50)")]
		public string LoaiHoa
		{
			get
			{
				return this._LoaiHoa;
			}
			set
			{
				if ((this._LoaiHoa != value))
				{
					this.OnLoaiHoaChanging(value);
					this.SendPropertyChanging();
					this._LoaiHoa = value;
					this.SendPropertyChanged("LoaiHoa");
					this.OnLoaiHoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MauHoa", DbType="NVarChar(50)")]
		public string MauHoa
		{
			get
			{
				return this._MauHoa;
			}
			set
			{
				if ((this._MauHoa != value))
				{
					this.OnMauHoaChanging(value);
					this.SendPropertyChanging();
					this._MauHoa = value;
					this.SendPropertyChanged("MauHoa");
					this.OnMauHoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KichThuoc", DbType="NVarChar(50)")]
		public string KichThuoc
		{
			get
			{
				return this._KichThuoc;
			}
			set
			{
				if ((this._KichThuoc != value))
				{
					this.OnKichThuocChanging(value);
					this.SendPropertyChanging();
					this._KichThuoc = value;
					this.SendPropertyChanged("KichThuoc");
					this.OnKichThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhuyenMai", DbType="Int")]
		public System.Nullable<int> KhuyenMai
		{
			get
			{
				return this._KhuyenMai;
			}
			set
			{
				if ((this._KhuyenMai != value))
				{
					this.OnKhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._KhuyenMai = value;
					this.SendPropertyChanged("KhuyenMai");
					this.OnKhuyenMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhHoa", DbType="NVarChar(MAX)")]
		public string AnhHoa
		{
			get
			{
				return this._AnhHoa;
			}
			set
			{
				if ((this._AnhHoa != value))
				{
					this.OnAnhHoaChanging(value);
					this.SendPropertyChanging();
					this._AnhHoa = value;
					this.SendPropertyChanged("AnhHoa");
					this.OnAnhHoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hoa_BinhLuan", Storage="_BinhLuans", ThisKey="MaHoa", OtherKey="MaHoa")]
		public EntitySet<BinhLuan> BinhLuans
		{
			get
			{
				return this._BinhLuans;
			}
			set
			{
				this._BinhLuans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hoa_ChiTietDonDatHang", Storage="_ChiTietDonDatHangs", ThisKey="MaHoa", OtherKey="MaHoa")]
		public EntitySet<ChiTietDonDatHang> ChiTietDonDatHangs
		{
			get
			{
				return this._ChiTietDonDatHangs;
			}
			set
			{
				this._ChiTietDonDatHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hoa_GioHang", Storage="_GioHangs", ThisKey="MaHoa", OtherKey="MaHoa")]
		public EntitySet<GioHang> GioHangs
		{
			get
			{
				return this._GioHangs;
			}
			set
			{
				this._GioHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.Hoa = this;
		}
		
		private void detach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.Hoa = null;
		}
		
		private void attach_ChiTietDonDatHangs(ChiTietDonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.Hoa = this;
		}
		
		private void detach_ChiTietDonDatHangs(ChiTietDonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.Hoa = null;
		}
		
		private void attach_GioHangs(GioHang entity)
		{
			this.SendPropertyChanging();
			entity.Hoa = this;
		}
		
		private void detach_GioHangs(GioHang entity)
		{
			this.SendPropertyChanging();
			entity.Hoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietDonDatHang")]
	public partial class ChiTietDonDatHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChiTietDonHang;
		
		private System.Nullable<int> _MaDonHang;
		
		private System.Nullable<int> _MaHoa;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<int> _GiaBanLe;
		
		private System.Nullable<int> _TongTien;
		
		private EntityRef<Hoa> _Hoa;
		
		private EntityRef<DonDatHang> _DonDatHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChiTietDonHangChanging(int value);
    partial void OnMaChiTietDonHangChanged();
    partial void OnMaDonHangChanging(System.Nullable<int> value);
    partial void OnMaDonHangChanged();
    partial void OnMaHoaChanging(System.Nullable<int> value);
    partial void OnMaHoaChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnGiaBanLeChanging(System.Nullable<int> value);
    partial void OnGiaBanLeChanged();
    partial void OnTongTienChanging(System.Nullable<int> value);
    partial void OnTongTienChanged();
    #endregion
		
		public ChiTietDonDatHang()
		{
			this._Hoa = default(EntityRef<Hoa>);
			this._DonDatHang = default(EntityRef<DonDatHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChiTietDonHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaChiTietDonHang
		{
			get
			{
				return this._MaChiTietDonHang;
			}
			set
			{
				if ((this._MaChiTietDonHang != value))
				{
					this.OnMaChiTietDonHangChanging(value);
					this.SendPropertyChanging();
					this._MaChiTietDonHang = value;
					this.SendPropertyChanged("MaChiTietDonHang");
					this.OnMaChiTietDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonHang", DbType="Int")]
		public System.Nullable<int> MaDonHang
		{
			get
			{
				return this._MaDonHang;
			}
			set
			{
				if ((this._MaDonHang != value))
				{
					if (this._DonDatHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDonHangChanging(value);
					this.SendPropertyChanging();
					this._MaDonHang = value;
					this.SendPropertyChanged("MaDonHang");
					this.OnMaDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoa", DbType="Int")]
		public System.Nullable<int> MaHoa
		{
			get
			{
				return this._MaHoa;
			}
			set
			{
				if ((this._MaHoa != value))
				{
					if (this._Hoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHoaChanging(value);
					this.SendPropertyChanging();
					this._MaHoa = value;
					this.SendPropertyChanged("MaHoa");
					this.OnMaHoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBanLe", DbType="Int")]
		public System.Nullable<int> GiaBanLe
		{
			get
			{
				return this._GiaBanLe;
			}
			set
			{
				if ((this._GiaBanLe != value))
				{
					this.OnGiaBanLeChanging(value);
					this.SendPropertyChanging();
					this._GiaBanLe = value;
					this.SendPropertyChanged("GiaBanLe");
					this.OnGiaBanLeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Int")]
		public System.Nullable<int> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hoa_ChiTietDonDatHang", Storage="_Hoa", ThisKey="MaHoa", OtherKey="MaHoa", IsForeignKey=true)]
		public Hoa Hoa
		{
			get
			{
				return this._Hoa.Entity;
			}
			set
			{
				Hoa previousValue = this._Hoa.Entity;
				if (((previousValue != value) 
							|| (this._Hoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Hoa.Entity = null;
						previousValue.ChiTietDonDatHangs.Remove(this);
					}
					this._Hoa.Entity = value;
					if ((value != null))
					{
						value.ChiTietDonDatHangs.Add(this);
						this._MaHoa = value.MaHoa;
					}
					else
					{
						this._MaHoa = default(Nullable<int>);
					}
					this.SendPropertyChanged("Hoa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonDatHang_ChiTietDonDatHang", Storage="_DonDatHang", ThisKey="MaDonHang", OtherKey="MaDonHang", IsForeignKey=true)]
		public DonDatHang DonDatHang
		{
			get
			{
				return this._DonDatHang.Entity;
			}
			set
			{
				DonDatHang previousValue = this._DonDatHang.Entity;
				if (((previousValue != value) 
							|| (this._DonDatHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonDatHang.Entity = null;
						previousValue.ChiTietDonDatHangs.Remove(this);
					}
					this._DonDatHang.Entity = value;
					if ((value != null))
					{
						value.ChiTietDonDatHangs.Add(this);
						this._MaDonHang = value.MaDonHang;
					}
					else
					{
						this._MaDonHang = default(Nullable<int>);
					}
					this.SendPropertyChanged("DonDatHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangKy")]
	public partial class DangKy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKhachHang;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _VaiTroNguoiDung;
		
		private string _TrangThai;
		
		private string _TenKhachHang;
		
		private string _DiaChi;
		
		private string _SoDienThoai;
		
		private string _Email;
		
		private string _AnhDaiDien;
		
		private EntitySet<BinhLuan> _BinhLuans;
		
		private EntitySet<DonDatHang> _DonDatHangs;
		
		private EntitySet<GioHang> _GioHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(int value);
    partial void OnMaKhachHangChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnVaiTroNguoiDungChanging(string value);
    partial void OnVaiTroNguoiDungChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnTenKhachHangChanging(string value);
    partial void OnTenKhachHangChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAnhDaiDienChanging(string value);
    partial void OnAnhDaiDienChanged();
    #endregion
		
		public DangKy()
		{
			this._BinhLuans = new EntitySet<BinhLuan>(new Action<BinhLuan>(this.attach_BinhLuans), new Action<BinhLuan>(this.detach_BinhLuans));
			this._DonDatHangs = new EntitySet<DonDatHang>(new Action<DonDatHang>(this.attach_DonDatHangs), new Action<DonDatHang>(this.detach_DonDatHangs));
			this._GioHangs = new EntitySet<GioHang>(new Action<GioHang>(this.attach_GioHangs), new Action<GioHang>(this.detach_GioHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VaiTroNguoiDung", DbType="NVarChar(20)")]
		public string VaiTroNguoiDung
		{
			get
			{
				return this._VaiTroNguoiDung;
			}
			set
			{
				if ((this._VaiTroNguoiDung != value))
				{
					this.OnVaiTroNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._VaiTroNguoiDung = value;
					this.SendPropertyChanged("VaiTroNguoiDung");
					this.OnVaiTroNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhachHang", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TenKhachHang
		{
			get
			{
				return this._TenKhachHang;
			}
			set
			{
				if ((this._TenKhachHang != value))
				{
					this.OnTenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._TenKhachHang = value;
					this.SendPropertyChanged("TenKhachHang");
					this.OnTenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(255)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(20)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhDaiDien", DbType="NVarChar(MAX)")]
		public string AnhDaiDien
		{
			get
			{
				return this._AnhDaiDien;
			}
			set
			{
				if ((this._AnhDaiDien != value))
				{
					this.OnAnhDaiDienChanging(value);
					this.SendPropertyChanging();
					this._AnhDaiDien = value;
					this.SendPropertyChanged("AnhDaiDien");
					this.OnAnhDaiDienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DangKy_BinhLuan", Storage="_BinhLuans", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<BinhLuan> BinhLuans
		{
			get
			{
				return this._BinhLuans;
			}
			set
			{
				this._BinhLuans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DangKy_DonDatHang", Storage="_DonDatHangs", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<DonDatHang> DonDatHangs
		{
			get
			{
				return this._DonDatHangs;
			}
			set
			{
				this._DonDatHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DangKy_GioHang", Storage="_GioHangs", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<GioHang> GioHangs
		{
			get
			{
				return this._GioHangs;
			}
			set
			{
				this._GioHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.DangKy = this;
		}
		
		private void detach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.DangKy = null;
		}
		
		private void attach_DonDatHangs(DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.DangKy = this;
		}
		
		private void detach_DonDatHangs(DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.DangKy = null;
		}
		
		private void attach_GioHangs(GioHang entity)
		{
			this.SendPropertyChanging();
			entity.DangKy = this;
		}
		
		private void detach_GioHangs(GioHang entity)
		{
			this.SendPropertyChanging();
			entity.DangKy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoanhThu")]
	public partial class DoanhThu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDoanhThu;
		
		private System.Nullable<int> _MaDonHang;
		
		private System.Nullable<System.DateTime> _NgayGiaoHang;
		
		private System.Nullable<int> _TongDoanhThu;
		
		private EntityRef<DonDatHang> _DonDatHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDoanhThuChanging(int value);
    partial void OnMaDoanhThuChanged();
    partial void OnMaDonHangChanging(System.Nullable<int> value);
    partial void OnMaDonHangChanged();
    partial void OnNgayGiaoHangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGiaoHangChanged();
    partial void OnTongDoanhThuChanging(System.Nullable<int> value);
    partial void OnTongDoanhThuChanged();
    #endregion
		
		public DoanhThu()
		{
			this._DonDatHang = default(EntityRef<DonDatHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoanhThu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDoanhThu
		{
			get
			{
				return this._MaDoanhThu;
			}
			set
			{
				if ((this._MaDoanhThu != value))
				{
					this.OnMaDoanhThuChanging(value);
					this.SendPropertyChanging();
					this._MaDoanhThu = value;
					this.SendPropertyChanged("MaDoanhThu");
					this.OnMaDoanhThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonHang", DbType="Int")]
		public System.Nullable<int> MaDonHang
		{
			get
			{
				return this._MaDonHang;
			}
			set
			{
				if ((this._MaDonHang != value))
				{
					if (this._DonDatHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDonHangChanging(value);
					this.SendPropertyChanging();
					this._MaDonHang = value;
					this.SendPropertyChanged("MaDonHang");
					this.OnMaDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGiaoHang", DbType="Date")]
		public System.Nullable<System.DateTime> NgayGiaoHang
		{
			get
			{
				return this._NgayGiaoHang;
			}
			set
			{
				if ((this._NgayGiaoHang != value))
				{
					this.OnNgayGiaoHangChanging(value);
					this.SendPropertyChanging();
					this._NgayGiaoHang = value;
					this.SendPropertyChanged("NgayGiaoHang");
					this.OnNgayGiaoHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongDoanhThu", DbType="Int")]
		public System.Nullable<int> TongDoanhThu
		{
			get
			{
				return this._TongDoanhThu;
			}
			set
			{
				if ((this._TongDoanhThu != value))
				{
					this.OnTongDoanhThuChanging(value);
					this.SendPropertyChanging();
					this._TongDoanhThu = value;
					this.SendPropertyChanged("TongDoanhThu");
					this.OnTongDoanhThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonDatHang_DoanhThu", Storage="_DonDatHang", ThisKey="MaDonHang", OtherKey="MaDonHang", IsForeignKey=true)]
		public DonDatHang DonDatHang
		{
			get
			{
				return this._DonDatHang.Entity;
			}
			set
			{
				DonDatHang previousValue = this._DonDatHang.Entity;
				if (((previousValue != value) 
							|| (this._DonDatHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonDatHang.Entity = null;
						previousValue.DoanhThus.Remove(this);
					}
					this._DonDatHang.Entity = value;
					if ((value != null))
					{
						value.DoanhThus.Add(this);
						this._MaDonHang = value.MaDonHang;
					}
					else
					{
						this._MaDonHang = default(Nullable<int>);
					}
					this.SendPropertyChanged("DonDatHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonDatHang")]
	public partial class DonDatHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDonHang;
		
		private System.Nullable<int> _MaKhachHang;
		
		private System.Nullable<System.DateTime> _NgayDatHang;
		
		private string _TenKhachHang;
		
		private string _DiaChiGiaoHang;
		
		private string _SoDienThoai;
		
		private string _TrangThaiDonHang;
		
		private System.Nullable<int> _TongGiaTriDonHang;
		
		private EntitySet<ChiTietDonDatHang> _ChiTietDonDatHangs;
		
		private EntitySet<DoanhThu> _DoanhThus;
		
		private EntityRef<DangKy> _DangKy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonHangChanging(int value);
    partial void OnMaDonHangChanged();
    partial void OnMaKhachHangChanging(System.Nullable<int> value);
    partial void OnMaKhachHangChanged();
    partial void OnNgayDatHangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatHangChanged();
    partial void OnTenKhachHangChanging(string value);
    partial void OnTenKhachHangChanged();
    partial void OnDiaChiGiaoHangChanging(string value);
    partial void OnDiaChiGiaoHangChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnTrangThaiDonHangChanging(string value);
    partial void OnTrangThaiDonHangChanged();
    partial void OnTongGiaTriDonHangChanging(System.Nullable<int> value);
    partial void OnTongGiaTriDonHangChanged();
    #endregion
		
		public DonDatHang()
		{
			this._ChiTietDonDatHangs = new EntitySet<ChiTietDonDatHang>(new Action<ChiTietDonDatHang>(this.attach_ChiTietDonDatHangs), new Action<ChiTietDonDatHang>(this.detach_ChiTietDonDatHangs));
			this._DoanhThus = new EntitySet<DoanhThu>(new Action<DoanhThu>(this.attach_DoanhThus), new Action<DoanhThu>(this.detach_DoanhThus));
			this._DangKy = default(EntityRef<DangKy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDonHang
		{
			get
			{
				return this._MaDonHang;
			}
			set
			{
				if ((this._MaDonHang != value))
				{
					this.OnMaDonHangChanging(value);
					this.SendPropertyChanging();
					this._MaDonHang = value;
					this.SendPropertyChanged("MaDonHang");
					this.OnMaDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Int")]
		public System.Nullable<int> MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._DangKy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDatHang", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDatHang
		{
			get
			{
				return this._NgayDatHang;
			}
			set
			{
				if ((this._NgayDatHang != value))
				{
					this.OnNgayDatHangChanging(value);
					this.SendPropertyChanging();
					this._NgayDatHang = value;
					this.SendPropertyChanged("NgayDatHang");
					this.OnNgayDatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhachHang", DbType="NVarChar(255)")]
		public string TenKhachHang
		{
			get
			{
				return this._TenKhachHang;
			}
			set
			{
				if ((this._TenKhachHang != value))
				{
					this.OnTenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._TenKhachHang = value;
					this.SendPropertyChanged("TenKhachHang");
					this.OnTenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiGiaoHang", DbType="NVarChar(255)")]
		public string DiaChiGiaoHang
		{
			get
			{
				return this._DiaChiGiaoHang;
			}
			set
			{
				if ((this._DiaChiGiaoHang != value))
				{
					this.OnDiaChiGiaoHangChanging(value);
					this.SendPropertyChanging();
					this._DiaChiGiaoHang = value;
					this.SendPropertyChanged("DiaChiGiaoHang");
					this.OnDiaChiGiaoHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(20)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiDonHang", DbType="NVarChar(20)")]
		public string TrangThaiDonHang
		{
			get
			{
				return this._TrangThaiDonHang;
			}
			set
			{
				if ((this._TrangThaiDonHang != value))
				{
					this.OnTrangThaiDonHangChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiDonHang = value;
					this.SendPropertyChanged("TrangThaiDonHang");
					this.OnTrangThaiDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongGiaTriDonHang", DbType="Int")]
		public System.Nullable<int> TongGiaTriDonHang
		{
			get
			{
				return this._TongGiaTriDonHang;
			}
			set
			{
				if ((this._TongGiaTriDonHang != value))
				{
					this.OnTongGiaTriDonHangChanging(value);
					this.SendPropertyChanging();
					this._TongGiaTriDonHang = value;
					this.SendPropertyChanged("TongGiaTriDonHang");
					this.OnTongGiaTriDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonDatHang_ChiTietDonDatHang", Storage="_ChiTietDonDatHangs", ThisKey="MaDonHang", OtherKey="MaDonHang")]
		public EntitySet<ChiTietDonDatHang> ChiTietDonDatHangs
		{
			get
			{
				return this._ChiTietDonDatHangs;
			}
			set
			{
				this._ChiTietDonDatHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonDatHang_DoanhThu", Storage="_DoanhThus", ThisKey="MaDonHang", OtherKey="MaDonHang")]
		public EntitySet<DoanhThu> DoanhThus
		{
			get
			{
				return this._DoanhThus;
			}
			set
			{
				this._DoanhThus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DangKy_DonDatHang", Storage="_DangKy", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public DangKy DangKy
		{
			get
			{
				return this._DangKy.Entity;
			}
			set
			{
				DangKy previousValue = this._DangKy.Entity;
				if (((previousValue != value) 
							|| (this._DangKy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DangKy.Entity = null;
						previousValue.DonDatHangs.Remove(this);
					}
					this._DangKy.Entity = value;
					if ((value != null))
					{
						value.DonDatHangs.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(Nullable<int>);
					}
					this.SendPropertyChanged("DangKy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDonDatHangs(ChiTietDonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.DonDatHang = this;
		}
		
		private void detach_ChiTietDonDatHangs(ChiTietDonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.DonDatHang = null;
		}
		
		private void attach_DoanhThus(DoanhThu entity)
		{
			this.SendPropertyChanging();
			entity.DonDatHang = this;
		}
		
		private void detach_DoanhThus(DoanhThu entity)
		{
			this.SendPropertyChanging();
			entity.DonDatHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GioHang")]
	public partial class GioHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaGioHang;
		
		private System.Nullable<int> _MaKhachHang;
		
		private System.Nullable<int> _MaHoa;
		
		private System.Nullable<int> _SoLuong;
		
		private EntityRef<Hoa> _Hoa;
		
		private EntityRef<DangKy> _DangKy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGioHangChanging(int value);
    partial void OnMaGioHangChanged();
    partial void OnMaKhachHangChanging(System.Nullable<int> value);
    partial void OnMaKhachHangChanged();
    partial void OnMaHoaChanging(System.Nullable<int> value);
    partial void OnMaHoaChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    #endregion
		
		public GioHang()
		{
			this._Hoa = default(EntityRef<Hoa>);
			this._DangKy = default(EntityRef<DangKy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGioHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaGioHang
		{
			get
			{
				return this._MaGioHang;
			}
			set
			{
				if ((this._MaGioHang != value))
				{
					this.OnMaGioHangChanging(value);
					this.SendPropertyChanging();
					this._MaGioHang = value;
					this.SendPropertyChanged("MaGioHang");
					this.OnMaGioHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Int")]
		public System.Nullable<int> MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._DangKy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoa", DbType="Int")]
		public System.Nullable<int> MaHoa
		{
			get
			{
				return this._MaHoa;
			}
			set
			{
				if ((this._MaHoa != value))
				{
					if (this._Hoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHoaChanging(value);
					this.SendPropertyChanging();
					this._MaHoa = value;
					this.SendPropertyChanged("MaHoa");
					this.OnMaHoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hoa_GioHang", Storage="_Hoa", ThisKey="MaHoa", OtherKey="MaHoa", IsForeignKey=true)]
		public Hoa Hoa
		{
			get
			{
				return this._Hoa.Entity;
			}
			set
			{
				Hoa previousValue = this._Hoa.Entity;
				if (((previousValue != value) 
							|| (this._Hoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Hoa.Entity = null;
						previousValue.GioHangs.Remove(this);
					}
					this._Hoa.Entity = value;
					if ((value != null))
					{
						value.GioHangs.Add(this);
						this._MaHoa = value.MaHoa;
					}
					else
					{
						this._MaHoa = default(Nullable<int>);
					}
					this.SendPropertyChanged("Hoa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DangKy_GioHang", Storage="_DangKy", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public DangKy DangKy
		{
			get
			{
				return this._DangKy.Entity;
			}
			set
			{
				DangKy previousValue = this._DangKy.Entity;
				if (((previousValue != value) 
							|| (this._DangKy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DangKy.Entity = null;
						previousValue.GioHangs.Remove(this);
					}
					this._DangKy.Entity = value;
					if ((value != null))
					{
						value.GioHangs.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(Nullable<int>);
					}
					this.SendPropertyChanged("DangKy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
